### ISSUE TITLE
Edge properties

### ISSUE THREAD

**Issue by patrickfuller** [patrickfuller/igraph#4]
From Uros Platise:

> I have one Q related to properties: would it be somehow possible to change individually arrow widths between nodes, in my case to represent the 'channel bandwidth' and colors, to depict some other properties of the channel (as missed slots, effective rates, etc.)

**Comment by platise** [comment]
Thanks for quick implementation.

Only the arrowSize parameter seems to confuse the draw():

"edges": [
        {"source": "chandler", "target": "ross", "color" : 0x2222ff, "size": 0.2},
        {"source": "monica", "target": "ross", "arrowSize": 1},
         ....

**Comment by patrickfuller** [comment]
9dea4e253355c4737c69352d50959252839af9c4 should fix the `arrowSize`.

**Comment by platise** [comment]
Super, it works now.
